version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    ignore:
      # 忽略所有主要版本更新
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: com.alibaba.cloud:spring-cloud-alibaba-dependencies
        versions:
          - ">= 2021.1"
