spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            # allowedOrigins: "*"
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: rose-upms-service
          uri: lb://rose-upms-service
          predicates:
            - Path=/upms/**

        - id: rose-auth
          uri: lb://rose-auth
          predicates:
            - Path=/auth/**

        - id: rose-example-swagger
          uri: lb://rose-example-swagger
          predicates:
            - Path=/swagger/**

        # 固定路由转发配置 无修改
        - id: openapi
          uri: lb://rose-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/$\{path}/v3/api-docs
