spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:rose-mysql}:${MYSQL_PORT:3306}/chensoul?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  activemq:
    broker-url: tcp://192.168.1.66:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50

# 租户表维护
mybatis-plus:
  tenant:
    ignoreTables:
      - sys_client
      - sys_log
      - sys_tenant
      - sys_user
      - sys_credential
